<?php
/**
 * WARNING PAGE 403|404|... error page
 *
 * @author       michael g
 * @author       Stura - Referat IT <ref-it@tu-ilmenau.de>
 * @since        17.02.2018
 * @copyright    Copyright (C) 2018 - All rights reserved
 */
$param = $param;
?>
<?php if (isset($param['image'])){
    echo '<div class="mt-3 mb-3" style="height: 300px; width: 400px; background-image:url(' . $param['image'] . '); background-repeat: no-repeat; background-position: center center; background-size: contain;"></div>';
} ?>
<h3><?= (isset($param['code']) ? $param['code'] : '') .
    ((isset($param['code']) && isset($param['headline'])) ? ' - ' : '') .
    (isset($param['headline']) ? $param['headline'] : '') ?></h3>
<p>
    Bitte melde diesen Fehler per
    <a href="<?= TG_ISSUE_LINK ?>"><i class="fa fa-fw fa-telegram"></i>Telegram</a> oder
    <a href="<?= GIT_ISSUE_LINK ?>?issuable_template=user_error_report"><i class="fa fa-fw fa-gitlab"></i>Gitlab</a> (Freischaltung evtl. erforderlich),
    damit er in Zukunft beseitigt werden kann.
</p>
<p><?= ($param['msg'] ? $param['msg'] : '') ?></p>
<div>
    <?php if (isset($param['additional'])){ ?>
        <h4><?= (isset($param['additional']['headline'])) ? $param['additional']['headline'] : 'Weitere Informationen' ?></h4>
        <p><?= (isset($param['additional']['msg'])) ? $param['additional']['msg'] : $param['additional'] ?></p>
    <?php } ?>
    <h5>Angeforderte Seite</h5>
    <span>&#62; <?php
        $protocol = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off') ? 'https://' : 'http://';
        echo htmlentities(urldecode($protocol . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'])); ?></span>
    <?php if (isset($_SERVER['HTTP_REFERER']) && $_SERVER['HTTP_REFERER']){ ?>
        <h5>Sie sind von folgender Seite hier gelandet</h5>
        <span>&#62; <a
                    href="<?= htmlentities(urldecode($_SERVER['HTTP_REFERER'])) ?>"><?= htmlentities(urldecode($_SERVER['HTTP_REFERER'])); ?></a></span>
    <?php } ?>


</div>
