<?php 
	$param = $param;
	$links = [];
	$headline = 'Nachricht';
	if (isset($param['headline'])){
		$headline = $param['headline'];
	}
	
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><!--[if IE]><html xmlns="http://www.w3.org/1999/xhtml" class="ie"><![endif]--><!--[if !IE]><!--><html style="margin: 0;padding: 0;" xmlns="http://www.w3.org/1999/xhtml"><!--<![endif]--><head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?= $headline ?></title>
    <!--[if !mso]><!--><meta http-equiv="X-UA-Compatible" content="IE=edge" /><!--<![endif]-->
    <meta name="viewport" content="width=device-width" />
<style type="text/css">
	body {
 		margin: 0;
		padding: 10px;
		height: 90%;
		width: 90%;
		background-color: #ffffff;
	}
	html {
		margin: 0;
		padding: 0;
		height: 100%;
		width: 100%;
	}
	table {
		border-collapse: collapse;
		table-layout: fixed;
	}
	* {
		line-height: inherit;
	}
</style>
    <meta name="robots" content="noindex,nofollow" />
	<meta property="og:title" content="<?= $headline ?>" />
</head>
<body class="half-padding" style="margin: 0;padding: 10px;-webkit-text-size-adjust: 100%;, height: 90%; width: 90%;">
	<h2><img style="display: inline-block;height: auto;width: 50px;border: 0;max-width: 242px; vertical-align: top; margin-right: 20px;" src="cid:logoattach" alt="Logo" width="242" /><?= $headline ?></h2>
	<hr>
	<?php 
		foreach ($param['msg'] as $msg){
			echo '<p>';
			foreach ($param['link'] as $k => $l){
				$c = count($links);
				$links[] = $l;
				$ltext = '<a href="'.$l.'">'.$k.'['.$c.']</a>';
				$msg = str_replace('%'.$k.'%', $ltext, $msg);
			}
			echo $msg;
			echo '</p>';
		}
	?>
	<?php 
	if (count($links) > 0){ ?>
		<hr>
		<h3>Links</h3>
		<p>
		<?php 
			$c = strlen(''.count($links));
			foreach ($links as $pos => $link){
				echo '['.str_pad($pos, $c, "0", STR_PAD_LEFT).'] - <a href="'.$link.'">'.$link.'</a><br>';
			}
		?>
		</p>
	<?php } ?>
	<p style="font-size: 8px; font-size: 0.7rem; font-weight: bold; color: #555555;">Diese Nachricht wurde automatisch vom Stura-FinanzTool generiert. Antworten Sie bitte nicht auf diese Nachricht.</p>
</body>
</html>