<?php 
	$param = $param; 
	$links = [];
?><?php 
if (isset($param['headline'])){
	echo ($param['headline']);
	echo "\n\n=================================================\n";
} ?>

<?php 
foreach ($param['msg'] as $msg){
	//replace links
	foreach ($param['link'] as $k => $l){
		$c = count($links);
		$links[] = $l;
		$ltext = $k.'['.$c.']';
		$msg = str_replace('%'.$k.'%', $ltext, $msg);
	}
	$msg = str_replace(['<br>', '<br/>'], "\n", $msg);
	$msg = strip_tags($msg);
	echo $msg;
	echo "\n\n";
}

if (count($links) > 0){
	echo "\nLinks\n----------------------\n\n";
	$c = strlen(''.count($links));
	foreach ($links as $pos => $link){
		echo '['.str_pad($pos, $c, "0", STR_PAD_LEFT).'] - '.$link."\n";
	}
}
?>

(Diese Nachricht wurde automatisch vom Stura-FinanzTool generiert. Antworten Sie bitte nicht auf diese Nachricht.)
