<?php


namespace framework\render\html;


use SVG\SVG;

class HtmlImage extends AbstractHtmlTag
{
    public static function make(string $altText) : self
    {
        return new self(['alt' => $altText]);
    }

    protected function __construct(array $attributes = [], array $classes = [], array $dataAttributes = [])
    {
        parent::__construct('img', $attributes, $classes, $dataAttributes);
    }

    public function srcLink(string $url) : self
    {
        $this->attr('src', $url);
        return $this;
    }

    public function srcBase64Encoded(string $encodedData, string $mimeType) : self
    {
        $this->attr('src', "data:image/$mimeType;base64,$encodedData");
        return $this;
    }

    public function __toString() : string
    {
        return $this->begin(); // TODO: Change the autogenerated stub
    }
}