<?php

return [
    'demo' => [
        'gremien' => [
            'Zentral' => [
                'Studierendenrat (StuRa)',
                'Wahlkommission Studierendenschaft',
                'Senat',
                'Konferenz Thüringer Studierendenschaften (KTS)',
                'Promovierendenvertretung',
            ],
            'Referate' => [
                'Referat Finanzen',
                'Referat Hochschulpolitik (HoPo)',
                'Referat IT',
                'Referat Kultur',
                'Referat Politische Bildung',
                'Referat Public Relations',
                'Referat Soziales',
                'Referat Sport Umwelt und Gesundheit (SUG)',
            ],
            'Fachschaftsräte' => [
                'Fachschaftsrat EI',
                'Fachschaftsrat IA',
                'Fachschaftsrat MB',
                'Fachschaftsrat MN',
                'Fachschaftsrat WM',
            ],
        ],
        'mailinglists' => [],
        'impressum-url' => 'https://open-administration.de/index.php/kontakt-und-impressum/',
        'datenschutz-url' => 'https://open-administration.de/index.php/datenschutz/',
        'issues-url' => '',
        'help-url' => 'mailto:service@open-administration.de',
        'mail-domain' => 'open-administration.de',
        'finanzen-mail' => 'lukas.staab@open-administration.de',
        'rechtsgrundlagen' => [
            'stura' => [
                'label' => 'StuRa-Beschluss',
                'label-additional' => 'Beschluss-Nr',
                'placeholder' => '',
                'hint-text' => 'Für FSR-Titel ist zusätzlich zum StuRa Beschluss zusätzlich ein FSR Beschluss notwendig.',
            ],
            'fsr-ref' => [
                'label' => 'Beschluss FSR/Referat/AG bis zu 250 EUR',
                'label-additional' => 'Beschluss-Nr (Verkündung)',
                'hint-text' => 'Interne Förderrichtlinie §6: für ein internes Projekt bis zu (inkl.) 250 EUR Muss auf der nächsten StuRa Sitzung vom HV bekannt gemacht werden.',
            ],
            'fahrt' => [
                'label' => 'Fahrtkosten',
                'hint-text' => 'Interne Förderrichtlinie §4a: Fahrtkosten',
            ],
            'buero' => [
                'label' => 'Büromaterial',
                'hint-text' => 'Interne Förderrichtlinie §3: bis zu 50 EUR',
            ],
            'andere' => [
                'label' => 'Andere Rechtsgrundlage',
                'label-additional' => 'Andere Rechtsgrundlage angeben',
                'hint-text' => '',
                'placeholder' => '',
            ],
        ],
        'projekt-form' => [
        ],
    ],
    'tui' => [
        'gremien' => [
            'Zentral' => [
                'Studierendenrat (StuRa)',
                'Wahlkommission Studierendenschaft',
                'Senat',
                'Studienausschuss',
                'Forschungsausschuss',
                'Gleichstellungsrat',
                'Konferenz Thüringer Studierendenschaften (KTS)',
                'Promovierendenvertretung',
            ],
            'Referate' => [
                'Referat Datenschutz',
                'Referat Ehrenamt',
                'Referat Erstiwoche',
                'Referat Finanzen',
                'Referat Hochschulpolitik (HoPo)',
                'Referat Interclub',
                'Referat Internationales',
                'Referat IT',
                'Referat Kultur',
                'Referat Politische Bildung',
                'Referat Public Relations',
                'Referat Soziales',
                'Referat Sport Umwelt und Gesundheit',
                'Referat Stadt',
            ],
            'Fachschaftsräte' => [
                'Fachschaftsrat EI',
                'Fachschaftsrat IA',
                'Fachschaftsrat MB',
                'Fachschaftsrat MN',
                'Fachschaftsrat WM',
            ],
            'Arbeitsgemeinschaften' => [
                'AG Diversity',
                'AG Mensaausschuss',
                'AG Ordnungen',
                'AG Umbau',
                'AG Promovierende',
            ],
            'Vereine' => [
                'Akademisches Orchester der TU Ilmenau e. V.',
                'Bergfest e. V.',
                'Forschungsgemeinschaft elektronische Medien e. V.',
                'Hochschulfilmclub e. V.',
                'hsf Studentenradio e. V.',
                'IEEE Student Branch Ilmenau',
                'SV TU Ilmenau e. V.',
                'Ilmenau eSport e. V.',
                'Ilmenauer Studentenclub e. V.',
                'ILMPULS e. V.',
                'Ingenieure ohne Grenzen e. V. (Ilmenau)',
                'Initiative Solidarische Welt Ilmenau e. V.',
                'Jazzclub Ilmenau e. V.',
                'Juso-Hochschulgruppe Ilmenau',
                'Kammerchor der TU Ilmenau e. V.',
                'Kulturelle Koordinierung e. V.',
                'Student Consulting Ilmenau e. V.',
                'SWING an der TU Ilmenau e. V.',
                'Team Starcraft e. V.',
                'VDE-Hochschulgruppe Ilmenau',
                'VDI Young Engineers',
                'Weitere Vereine und Organisationen',
            ],
        ],
        'mailinglists' => [],
        'impressum-url' => 'https://open-administration.de/index.php/kontakt-und-impressum/',
        'datenschutz-url' => 'https://open-administration.de/index.php/datenschutz/',
        'issues-url' => '',
        'help-url' => 'mailto:service@open-administration.de',
        'mail-domain' => 'tu-ilmenau.de',
        'finanzen-mail' => 'lukas.staab@tu-ilmenau.de',
        'rechtsgrundlagen' => [
            'stura' => [
                'label' => 'StuRa-Beschluss',
                'label-additional' => 'Beschluss-Nr',
                'placeholder' => '',
                'hint-text' => 'Für FSR-Titel ist zusätzlich zum StuRa Beschluss zusätzlich ein FSR Beschluss notwendig.',
            ],
            'fsr-ref' => [
                'label' => 'Beschluss 250€',
                'label-additional' => 'Beschluss-Nr (Verkündung)',
                'hint-text' => 'Förderrichtlinie §13 Abs. 1: für ein internes Projekt bis zu (inkl.) 250 EUR Muss auf der nächsten StuRa Sitzung vom HV verkündet werden.',
            ],
            'kleidung' => [
                'label' => 'Gremienkleidung',
                'hint-text' => 'Förderrichtlinie §14: bis zu 30€ pro Person (pro Gremium und Legislatur). Für Aktive Beschluss notwendig.',
            ],
            'fahrt' => [
                'label' => 'Fahrtkosten',
                'hint-text' => 'Förderrichtlinie §12 Abs. 1, 2',
            ],
            'verbrauch' => [
                'label' => 'Verbrauchsmaterial',
                'hint-text' => 'Finanzordnung §11 Abs 3: bis zu 150 €',
            ],
            'bahn-card' => [
                'label' => 'Bahncard',
                'hint-text' => 'Förderrichtlinie §12 Abs. 3: Privat gekaufte Bahn-Cards, falls für den StuRa die Anschaffung der Bahncard nachweislich günstiger war.',
            ],
            'andere' => [
                'label' => 'Andere Rechtsgrundlage',
                'label-additional' => 'Andere Rechtsgrundlage angeben',
                'hint-text' => '',
                'placeholder' => '',
            ],
        ],
        'projekt-form' => [
            'protokoll-prefix' => 'https://wiki.stura-ilmenau.de/protokoll/',
        ],
    ],
    'ue' => [
        'gremien' => [
            'Zentral' => [
                'StuRa Vorstand',
                'Antidiskriminierungsstelle',
                'Fachschaftsratsbeauftragte*r',
                'Hochschulgruppenbeauftragte*r',
            ],
            'Referate' => [
                'Referat Finanzen',
                'Referat Hochschulpolitik',
                'Referat Öffentlichkeitsarbeit',
                'Referat Kultur',
                'Referat Sozialpolitik und Soziales',
                'Referat Internes',
                'Referat Internationales',
                'Referat Nachhaltigkeit',
                'Referat Sport',
            ],
            'Philosophische Fakultät' => [
                'FSR Anglistik',
                'FSR Germanistik',
                'FSR Geschichte',
                'FSR KW',
                'FSR Literaturwissenschaft',
                'FSR Philosophie',
                'FSR Religionswissenschaft',
                'FSR Romanistik',
            ],
            'Erziehungswissenschaftliche Fakultät' => [
                'FSR EW',
                'FSR FSI',
                'FSR Kunst',
                'FSR Lehramt',
                'FSR Master Lehramt',
                'FSR Musik',
                'FSR PEB',
                'FSR Psychologie',
                'FSR Sport',
                'FSR Technik',
            ],
            'Staatswissenschaftliche Fakultät' => [
                'FSR StaWi',
            ],
            'Katholisch-Theologische Fakultät' => [
                'FSR Kath. Theologie',
            ],
            'Sonstiges' => [
                'Hochschulgruppe (divers)',
                'sonst. Studentische Initiativen',
            ],
        ],
        'rechtsgrundlagen' => [
            'stura' => [
                'label' => 'StuRa-Beschluss',
                'label-additional' => 'Beschluss-Nr',
                'placeholder' => '',
                'hint-text' => '',
            ],
            'vorstand' => [
                'label' => 'Vorstandsbeschluss',
                'label-additional' => 'Beschluss-Nr',
                'placeholder' => '',
                'hint-text' => '',
            ],
            'fo-5a' => [
                'label' => 'FO5a (Referate)',
                'hint-text' => 'Interne Genehmigung durch Finanzreferenten',
            ],
            'fo-93a' => [
                'label' => 'FO93b (FSRs durch Finanzreferat)',
                'hint-text' => 'Externe Genehmigung durch Finanzreferat bis 250€',
            ],
            'fo-93b' => [
                'label' => 'FO93b (Kleidung)',
                'hint-text' => 'Externe Genehmigung durch Finanzreferat von Öffentlichkeitswirksamer Kleidung bis 510 bei max. 30 € pro Person',
            ],
            'fo-93c' => [
                'label' => 'FO93b (Teambuilding)',
                'hint-text' => 'Externe Genehmigung durch Finanzreferat von bis zu 75% der Kosten und max. 15€ pro Person',
            ],
        ],
        'mailinglists' => [],
        'impressum-url' => 'https://open-administration.de/index.php/kontakt-und-impressum/',
        'datenschutz-url' => 'https://open-administration.de/index.php/datenschutz/',
        'issues-url' => '',
        'help-url' => 'mailto:service@open-administration.de',
        'mail-domain' => 'uni-erfurt.de',
        'finanzen-mail' => 'lukas.staab@tu-ilmenau.de',
        'projekt-form' => [
            'hide-protokoll',
        ],
    ],
    'hs-sm' => [
        'gremien' => [
            'Zentral' => [
                'StuRa',
                'StuRa Vorstand',
                'Kultur',
                'KTS',
            ],
            'Referate' => [
                'Referat Finanzen',
                'Referat IT',
                'Referat Merchandise',
                'Referat für öffentliche Arbeit',
            ],
            'Fachschaftsräte' => [
                'FSR Elektrotechnik',
                'FSR Informatik',
                'FSR Maschinenbau',
                'FSR Wirtschaftsrecht',
                'FSR Wirtschaftswissenschaften',
            ],
            'Widerkehrendes' => [
                'Schmalympics',
                'Semesteranfangsparty Sommersemester',
                'Semesteranfangsparty Wintersemester',
                'Prüfungsabschlussparty Sommersemester',
                'Prüfungsabschlussparty Wintersemester',
            ],
        ],
        'rechtsgrundlagen' => [
            'stura' => [
                'label' => 'StuRa-Beschluss',
                'label-additional' => 'Beschluss-Nr',
                'placeholder' => '',
                'hint-text' => '',
            ],
        ],
        'mailinglists' => [],
        'impressum-url' => 'https://open-administration.de/index.php/kontakt-und-impressum/',
        'datenschutz-url' => 'https://open-administration.de/index.php/datenschutz/',
        'issues-url' => '',
        'help-url' => 'mailto:service@open-administration.de',
        'mail-domain' => 'hs-schmalkalden.de',
        'finanzen-mail' => 'lukas.staab@tu-ilmenau.de',
        'projekt-form' => [
            'hide-protokoll',
        ],
    ],
    'eah' => [
        'gremien' => [
            'Zentral' => [
                'Studierendenrat (StuRa)',
                'Konferenz Thüringer Studierendenschaften (KTS)',
                'Senat',
            ],
            'Referate' => [
                'Referat Finanzen',
                'Referat Hochschulpolitik',
                'Referat Hochschulsport',
                'Referat Internationale Kultur',
                'Referat Koordination studentischer Gremien',
                'Referat Kultur',
                'Referat Öffentlichkeitsarbeit',
                'Referat Semesterticket',
                'Referat Soziales',
                'Referat Technik',
                'Referat Umwelt',
            ],
            'Fachschaftsräte' => [
                'Fachschaftsrat BW',
                'Fachschaftsrat ET/IT',
                'Fachschaftsrat GP',
                'Fachschaftsrat MT/BT',
                'Fachschaftsrat SciTec und MB',
                'Fachschaftsrat SW',
                'Fachschaftsrat WI',
            ],
            'Weitere' => [
                'Akrützel',
                'Campusradio',
                'Mitarbeiter',
                'Professor',
                'Studenten',
                'Externe Dritte',
            ],
        ],
        'mailinglists' => [],
        'impressum-url' => 'https://open-administration.de/index.php/kontakt-und-impressum/',
        'datenschutz-url' => 'https://open-administration.de/index.php/datenschutz/',
        'issues-url' => '',
        'help-url' => 'mailto:service@open-administration.de',
        'mail-domain' => 'eah-jena.de',
        'finanzen-mail' => 'stura@eah-jena.de',
        'rechtsgrundlagen' => [
            'stura' => [
                'label' => 'StuRa-Beschluss',
                'label-additional' => 'Datum und TOP',
                'placeholder' => '',
                //'hint-text' => 'Hier ist Platz für einen hilfreichen Text.',
            ],
            'stura-vorstand' => [
                'label' => 'StuRa Vorstandsbeschluss',
                'label-additional' => 'Datum und TOP',
                //'hint-text' => 'Hier ist Platz für einen hilfreichen Text.',
            ],
            'fsr' => [
                'label' => 'FSR Beschluss',
                'label-additional' => 'Datum und TOP',
                //'hint-text' => 'Hier ist Platz für einen hilfreichen Text.',
            ],
            'mittel' => [
                'label' => 'Antrag auf Mittelfreigabe',
                'hint-text' => 'Interne Förderrichtlinie §41 (7), (8). sowie §42: StuRa bis zu 100 EUR & FSRe bis zu 75 EUR',
            ],
            'vertrag' => [
                'label' => 'Verträge',
                //'hint-text' => 'Hier ist Platz für einen hilfreichen Text.',
            ],
            'ordnung' => [
                'label' => 'Ordnungen oder Satzung',
                //'hint-text' => 'Hier ist Platz für einen hilfreichen Text.',
            ],
        ],
        'projekt-form' => [
        ],
    ],
    'rh' => [
        'gremien' => [
            'Zentral' => [
                'Allgemeiner Studierendenausschuss (AStA)',
                'AStA Vorstand',
                'Finanzteam',
                'Studierendenschaft',
            ],
        ],
        'mailinglists' => [],
        'impressum-url' => 'https://open-administration.de/index.php/kontakt-und-impressum/',
        'datenschutz-url' => 'https://open-administration.de/index.php/datenschutz/',
        'issues-url' => '',
        'help-url' => 'mailto:service@open-administration.de',
        'mail-domain' => 'astarauheshaus.de',
        'finanzen-mail' => 'lukas.staab@open-administration.de',
        'rechtsgrundlagen' => [
            'asta' => [
                'label' => 'AStA-Beschluss',
                'label-additional' => 'Sitzungsdatum',
                'placeholder' => '',
                'hint-text' => 'Hier ist Platz für einen hilfreichen Text.',
            ],
            'andere' => [
                'label' => 'Andere Rechtsgrundlage',
                'label-additional' => 'Andere Rechtsgrundlage angeben',
                'hint-text' => '',
                'placeholder' => '',
            ],
        ],
        'projekt-form' => [
        ],
    ],
    'fhe' => [
        'gremien' => [
            'Zentral' => [
                'Studierendenrat (StuRa)',
            ],
            'Fachschaftsräte' => [
                'FSR Angewandte Informatik',
                'FSR Landschaftsarchitektur, Gartenbau und Forst',
                'FSR Angewandte Sozialwissenschaften',
                'FSR Stadt- & Raumplanung',
                'FSR Wirtschaftswissenschaften',
                'FSR Verkehr- & Transportwesen',
                'FSR Bauingeneurwesen',
                'FSR Architektur',
                'FSR Gebäude- & Energietechnik',
            ],
            'Hochschulgruppen' => [
                'AG Nachhaltigkeit',
                'AreYouOkay Stud Pro FH Erfurt (Awareness)',
                'Betonkanu',
                'Café Aquarium',
                'Fahrradwerkstatt',
                'Film-AG',
                'Foodsharing',
                'HipoA',
                'Lautstark gegen Faschismus',
                'Hochschulliga',
                'NagNag',
                'Neurospektrum',
                'Queerfurt',
                'AG Spieleabend',
                'Theater AG',
                'Werkraum',
                'DigIT',
                'Arbeitsgemeinschaft naturgemäße Waldwirtschaft',
                'Liberale Hochschulgruppe',
                'Studierende für Christus',
                'Evangelische Studierenden Gemeinde',
                'Studierengärten',
            ],
        ],
        'mailinglists' => [],
        'impressum-url' => 'https://open-administration.de/index.php/kontakt-und-impressum/',
        'datenschutz-url' => 'https://open-administration.de/index.php/datenschutz/',
        'issues-url' => '',
        'help-url' => 'mailto:service@open-administration.de',
        'mail-domain' => 'fh-erfurt.de',
        'finanzen-mail' => 'finanzen.stura@fh-erfurt.de',
        'rechtsgrundlagen' => [
            'stura' => [
                'label' => 'StuRa-Beschluss',
                'label-additional' => 'Beschluss-Nr',
                'placeholder' => '',
                'hint-text' => 'Beschluss des Studierendenrates gem. Finanzordnung §12 (1)',
            ],
            'buero' => [
                'label' => 'Büromaterial',
                'hint-text' => '150€ Büromaterial gem. Finanzordnung §12 (3)',
            ],
            'umlauf' => [
                'label' => 'Umlaufbeschluss',
                'label-additional' => 'Beschluss-Nr',
                'placeholder' => '',
                'hint-text' => 'Umlaufbeschluss gem. Geschäftsordnung §14 (3)',
            ],
            'andere' => [
                'label' => 'Andere Rechtsgrundlage',
                'label-additional' => 'Andere Rechtsgrundlage angeben',
                'hint-text' => '',
                'placeholder' => '',
            ],
        ],
        'projekt-form' => [
        ],
    ],

];
